### ISSUE TITLE
SA2 PC Blender Addon textures all white

### ISSUE THREAD

**Issue by dqf318** [sonicretro/sa_tools#155]
I tried to import a stage from SA2 to the Blender addon, but for some reason, the textures don't apply in Blender.  They all come out as white.

**Comment by ItsEasyActually** [comment]
Please follow this guide to properly import models: https://github.com/Justin113D/BlenderSASupport/wiki/Ripping-models

Do note some levels, particularly Dry Lagoon, have issues due to the SA2B model format not having official documentation.

If you have further issues, please post them to the [BlenderSASupport repo](https://github.com/Justin113D/BlenderSASupport). This repo is for the SA Tools, and the Blender addon is separate.
